/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchesRouteImport } from './routes/watches'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PerfumesRouteImport } from './routes/perfumes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FashionRouteImport } from './routes/fashion'
import { Route as ElectronicsRouteImport } from './routes/electronics'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'

const WatchesRoute = WatchesRouteImport.update({
  id: '/watches',
  path: '/watches',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfumesRoute = PerfumesRouteImport.update({
  id: '/perfumes',
  path: '/perfumes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FashionRoute = FashionRouteImport.update({
  id: '/fashion',
  path: '/fashion',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectronicsRoute = ElectronicsRouteImport.update({
  id: '/electronics',
  path: '/electronics',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/books': typeof BooksRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/electronics': typeof ElectronicsRoute
  '/fashion': typeof FashionRoute
  '/login': typeof LoginRoute
  '/perfumes': typeof PerfumesRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/signup': typeof SignupRoute
  '/watches': typeof WatchesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/electronics': typeof ElectronicsRoute
  '/fashion': typeof FashionRoute
  '/login': typeof LoginRoute
  '/perfumes': typeof PerfumesRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/signup': typeof SignupRoute
  '/watches': typeof WatchesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/books': typeof BooksRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/electronics': typeof ElectronicsRoute
  '/fashion': typeof FashionRoute
  '/login': typeof LoginRoute
  '/perfumes': typeof PerfumesRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/signup': typeof SignupRoute
  '/watches': typeof WatchesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/books'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/electronics'
    | '/fashion'
    | '/login'
    | '/perfumes'
    | '/profile'
    | '/search'
    | '/shipping'
    | '/signup'
    | '/watches'
    | '/admin/orders'
    | '/admin/products'
    | '/products/$productId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/books'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/electronics'
    | '/fashion'
    | '/login'
    | '/perfumes'
    | '/profile'
    | '/search'
    | '/shipping'
    | '/signup'
    | '/watches'
    | '/admin/orders'
    | '/admin/products'
    | '/products/$productId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/books'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/electronics'
    | '/fashion'
    | '/login'
    | '/perfumes'
    | '/profile'
    | '/search'
    | '/shipping'
    | '/signup'
    | '/watches'
    | '/admin/orders'
    | '/admin/products'
    | '/products/$productId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BooksRoute: typeof BooksRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  ElectronicsRoute: typeof ElectronicsRoute
  FashionRoute: typeof FashionRoute
  LoginRoute: typeof LoginRoute
  PerfumesRoute: typeof PerfumesRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  ShippingRoute: typeof ShippingRoute
  SignupRoute: typeof SignupRoute
  WatchesRoute: typeof WatchesRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watches': {
      id: '/watches'
      path: '/watches'
      fullPath: '/watches'
      preLoaderRoute: typeof WatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfumes': {
      id: '/perfumes'
      path: '/perfumes'
      fullPath: '/perfumes'
      preLoaderRoute: typeof PerfumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fashion': {
      id: '/fashion'
      path: '/fashion'
      fullPath: '/fashion'
      preLoaderRoute: typeof FashionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electronics': {
      id: '/electronics'
      path: '/electronics'
      fullPath: '/electronics'
      preLoaderRoute: typeof ElectronicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BooksRoute: BooksRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  ElectronicsRoute: ElectronicsRoute,
  FashionRoute: FashionRoute,
  LoginRoute: LoginRoute,
  PerfumesRoute: PerfumesRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  ShippingRoute: ShippingRoute,
  SignupRoute: SignupRoute,
  WatchesRoute: WatchesRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
