/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchesRouteImport } from './routes/watches'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as PerfumesRouteImport } from './routes/perfumes'
import { Route as FashionRouteImport } from './routes/fashion'
import { Route as ElectronicsRouteImport } from './routes/electronics'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BooksRouteImport } from './routes/books'
import { Route as IndexRouteImport } from './routes/index'

const WatchesRoute = WatchesRouteImport.update({
  id: '/watches',
  path: '/watches',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfumesRoute = PerfumesRouteImport.update({
  id: '/perfumes',
  path: '/perfumes',
  getParentRoute: () => rootRouteImport,
} as any)
const FashionRoute = FashionRouteImport.update({
  id: '/fashion',
  path: '/fashion',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectronicsRoute = ElectronicsRouteImport.update({
  id: '/electronics',
  path: '/electronics',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/electronics': typeof ElectronicsRoute
  '/fashion': typeof FashionRoute
  '/perfumes': typeof PerfumesRoute
  '/shipping': typeof ShippingRoute
  '/watches': typeof WatchesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/electronics': typeof ElectronicsRoute
  '/fashion': typeof FashionRoute
  '/perfumes': typeof PerfumesRoute
  '/shipping': typeof ShippingRoute
  '/watches': typeof WatchesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/contact': typeof ContactRoute
  '/electronics': typeof ElectronicsRoute
  '/fashion': typeof FashionRoute
  '/perfumes': typeof PerfumesRoute
  '/shipping': typeof ShippingRoute
  '/watches': typeof WatchesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/books'
    | '/contact'
    | '/electronics'
    | '/fashion'
    | '/perfumes'
    | '/shipping'
    | '/watches'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/books'
    | '/contact'
    | '/electronics'
    | '/fashion'
    | '/perfumes'
    | '/shipping'
    | '/watches'
  id:
    | '__root__'
    | '/'
    | '/books'
    | '/contact'
    | '/electronics'
    | '/fashion'
    | '/perfumes'
    | '/shipping'
    | '/watches'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksRoute: typeof BooksRoute
  ContactRoute: typeof ContactRoute
  ElectronicsRoute: typeof ElectronicsRoute
  FashionRoute: typeof FashionRoute
  PerfumesRoute: typeof PerfumesRoute
  ShippingRoute: typeof ShippingRoute
  WatchesRoute: typeof WatchesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watches': {
      id: '/watches'
      path: '/watches'
      fullPath: '/watches'
      preLoaderRoute: typeof WatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfumes': {
      id: '/perfumes'
      path: '/perfumes'
      fullPath: '/perfumes'
      preLoaderRoute: typeof PerfumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fashion': {
      id: '/fashion'
      path: '/fashion'
      fullPath: '/fashion'
      preLoaderRoute: typeof FashionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electronics': {
      id: '/electronics'
      path: '/electronics'
      fullPath: '/electronics'
      preLoaderRoute: typeof ElectronicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksRoute: BooksRoute,
  ContactRoute: ContactRoute,
  ElectronicsRoute: ElectronicsRoute,
  FashionRoute: FashionRoute,
  PerfumesRoute: PerfumesRoute,
  ShippingRoute: ShippingRoute,
  WatchesRoute: WatchesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
